# Generated by Django 5.2.7 on 2025-10-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('genero', models.CharField(choices=[('PES', 'Pessoal'), ('PRO', 'Projetos')], default='PES', max_length=3)),
                ('vezes_respondida', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-vezes_respondida', '-criado_em'],
            },
        ),
    ]
