# Generated by Django 5.2.7 on 2025-10-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='genero',
            field=models.CharField(choices=[('BIO', 'Biografia'), ('OBR', 'Obras'), ('ACO', 'Ações do governo')], default='PES', max_length=3),
        ),
    ]
